---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclouddatabases.composite.clouddatabase.allianz.io
  namespace: customer
spec:
  group: composite.clouddatabase.allianz.io
  names:
    kind: XClouddatabase
    plural: xclouddatabases
  claimNames:
    kind: clouddatabase
    plural: clouddatabases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                    default: eu-central-1
                    enum:
                    - eu-central-1
                    - eu-west-3
                  region_secondary:
                    type: string
                    default: default
                    enum:
                    - default
                    - eu-west-3
                    - eu-west-1
                  account_name:
                    type: string
                    default: clouddatabase
                  deployment_variables:
                    type: object
                    properties:
                      global_cluster_name:
                        type: string
                      global_engine_version:
                        type: string
                      global_storage_encrypted:
                        type: boolean
                      deletion_protection:
                        type: boolean
                        default: true
                      aurora_clusters:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            location:
                              type: string
                              default: primary
                              enum:
                              - "primary"
                              - "secondary"
                            engine_version:
                              type: string
                            deletion_protection:
                              type: boolean
                              default: true
                            snapshot_identifier:
                              type: string
                            database_name:
                              type: string
                            username:
                              type: string
                            password:
                              type: string
                            skip_final_snapshot:
                              type: boolean
                            storage_type:
                              type: string
                            backtrack_window:
                              type: string
                            backup_retention_period:
                              type: string
                            preferred_backup_window:
                              type: string
                            preferred_maintenance_window:
                              type: string
                              default: wed:04:00-wed:04:30
                            enabled_cloudwatch_logs_export:
                              type: array
                              items:
                                type: string
                            final_snapshot_identifier:
                              type: string
                            port:
                              type: string
                            tags:
                              type: object
                            subnet_ids:
                              type: array
                              items:
                                type: string
                            prepare_upgrade:
                              type: boolean
                              default: false
                            parametergroup:
                              type: object
                              default: {}
                              properties:
                                name:
                                  type: string
                                entries:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      name:
                                        type: string
                                      value:
                                        type: string
                                      apply_method:
                                        type: string
                                        default: pending-reboot
                                        enum:
                                        - pending-reboot
                                        - immediate
                            instances:
                              type: array
                              items:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  size:
                                    type: string
                                  apply_immediately:
                                    type: string
                                    enum:
                                    - "true"
                                    - "false"
                                  preferred_maintenance_window:
                                    type: string
                                  monitoring_role_arn:
                                    type: string
                                  monitoring_interval:
                                    type: string
                                  auto_minor_version_upgrade:
                                    type: string
                                  performance_insights_enabled:
                                    type: string
                                  tags:
                                    type: object
                                  parametergroup:
                                    type: object
                                    default: {}
                                    properties:
                                      name:
                                        type: string
                                      entries:
                                        type: array
                                        items:
                                          type: object
                                          properties:
                                            name:
                                              type: string
                                            value:
                                              type: string
                                            apply_method:
                                              type: string
                                              default: pending-reboot
                                              enum:
                                              - pending-reboot
                                              - immediate
                            security_group:
                              type: array
                              items:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  vpc_id:
                                    type: string
                                  egress:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        description:
                                          type: string
                                        from_port:
                                          type: string
                                        to_port:
                                          type: string
                                        protocol:
                                          type: string
                                        cidr_blocks:
                                          type: array
                                          items:
                                            type: string
                                        security_groups:
                                          type: array
                                          items:
                                            type: string
                                  ingress:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        description:
                                          type: string
                                        from_port:
                                          type: string
                                        to_port:
                                          type: string
                                        protocol:
                                          type: string
                                        cidr_blocks:
                                          type: array
                                          items:
                                            type: string
                                        security_groups:
                                          type: array
                                          items:
                                            type: string
                                required:
                                - name
                          required:
                          - name
                required:
                - region
                - deployment_variables
            required:
            - parameters
