---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdynatracedashboardtests.composite.clouddatabase.allianz.io
  namespace: customer
spec:
  group: composite.clouddatabase.allianz.io
  names:
    kind: XDynatraceDashboardTest
    plural: xdynatracedashboardtests
  claimNames:
    kind: dynatracedashboardtest
    plural: dynatracedashboardtests
  defaultCompositionRef:
    name: xdynatracedashboardtests.composite.clouddatabase.allianz.io
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  dashboard_name:
                    type: string
                    default: ""
                  github_owner:
                    type: string
                    default: "globalmonitoring"
                  github_token:
                    type: string
                    default: ""
                  customer_repository:
                    type: string
                    default: ""
                  dynatrace_management_zone:
                    type: string
                    default: ""
                  dynatrace_alerting_profile:
                    type: string
                    default: "default.yml"
                  snow_f_group:
                    type: string
                    default: ""
                  email_recepients:
                    type: string
                    default: ""
                  notification_email:
                    type: string
                    default: "true"
                  notification_snow:
                    type: string
                    default: "false"
                  notification_zis:
                    type: string
                    default: "true"
                  param1_name:
                    type: string
                    default: "CPU Usage"
                  param1_graph:
                    type: string
                    default: "builtin:cloud.aws.rds.cpu.usage"
                  param1_aggregation:
                    type: string
                    default: "AVG"
                  param1_condition:
                    type: string
                    default: "ABOVE"
                  param1_threshold_orange:
                    type: string
                    default: "95"
                  param1_threshold_red:
                    type: string
                    default: "99"
                  param2_name:
                    type: string
                    default: "Read IOPS"
                  param2_graph:
                    type: string
                    default: "builtin:cloud.aws.rds.ops.read"
                  param2_aggregation:
                    type: string
                    default: "AVG"
                  param2_condition:
                    type: string
                    default: "ABOVE"
                  param2_threshold_orange:
                    type: string
                    default: "10000"
                  param2_threshold_red:
                    type: string
                    default: "20000"
                  param3_name:
                    type: string
                    default: "Write IOPS"
                  param3_graph:
                    type: string
                    default: "builtin:cloud.aws.rds.ops.write"
                  param3_aggregation:
                    type: string
                    default: "AVG"
                  param3_condition:
                    type: string
                    default: "ABOVE"
                  param3_threshold_orange:
                    type: string
                    default: "10000"
                  param3_threshold_red:
                    type: string
                    default: "20000"
                  param4_name:
                    type: string
                    default: "SWAP Usage"
                  param4_graph:
                    type: string
                    default: "builtin:cloud.aws.rds.memory.swap"
                  param4_aggregation:
                    type: string
                    default: "AVG"
                  param4_condition:
                    type: string
                    default: "ABOVE"
                  param4_threshold_orange:
                    type: string
                    default: "3.5"
                  param4_threshold_red:
                    type: string
                    default: "4"
                  param5_name:
                    type: string
                    default: "Free Memory"
                  param5_graph:
                    type: string
                    default: "builtin:cloud.aws.rds.memory.freeable"
                  param5_aggregation:
                    type: string
                    default: "AVG"
                  param5_condition:
                    type: string
                    default: "BELOW"
                  param5_threshold_orange:
                    type: string
                    default: "100"
                  param5_threshold_red:
                    type: string
                    default: "50"
                  meta_dynatrace_management_zone:
                    type: string
                    default: ""
                  meta_customer_repository:
                    type: string
                    default: ""
                  provider_configuration:
                    type: string
                    default: github-4-dynatrace-v1
                  db_tags:
                    type: array
                    default: []
                    items:
                      type: string
                required:
                - dashboard_name
                - db_tags
            required:
            - parameters
