---
apiVersion: composite.clouddatabase.allianz.io/v1alpha1
kind: Dynatrace
metadata:
  name: dynatrace-deployment
  namespace: customer
spec:
  parameters:
    provider_configuration: aws-clouddatabase-v2
    dashboard_name: "Dagobert"
    github_token: "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"
    customer_repository: "preprod-mz-az-tech-dagobert"
    dynatrace_management_zone: "mz-az-tech-dagobert"
    snow_f_group: "AZD.BIT-KVI5.CO-AZDCLOUD"
    email_recipients: "extern.binder_david@allianz.de"
    db_tags: "[AWS]dynatrace"